version: '3.7'
services:
  prod_server:
    build: ./prod_server
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - ./prod_server:/usr/src/app
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - APP_SETTINGS=config.DevelopmentConfig

  frontend:
    build: ./frontend
    expose:
      - 3000
    ports:
      - 3000:3000
    # env_file:
    #   - .env
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
    environment:
      - HOST=0.0.0.0
    links:
      - "prod_server:prod_server"
    